service: aws-crudAPI-sls
# frameworkVersion: '3'
custom:
  settings:
    DB_TABLE: myTable

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:*
        Resource:
          - arn:aws:dynamodb:us-east-1:710210764707:table/myTable
          # - "arm:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.DB_TABLE}"

functions:
  hello:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  listTask:
    handler: src/listTask.listTask
    events:
      - httpApi:
          path: /task
          method: get
  createTask:
    handler: src/addTask.addTask
    events:
      - httpApi:
          path: /task
          method: post 
  getTask:
    handler: src/getTask.getTask
    events:
      - httpApi:
          path: /task/{id}
          method: get 
  updateTask:
    handler: src/updateTask.updateTask
    events:
      - httpApi:
          path: /task/{id}
          method: put
  deleteTask:
    handler: src/deleteTask.deleteTask 
    events:
      - httpApi:
          path: /task/{id}
          method: delete
resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # TableName: ${self:custom.settings.DB_TABLE}
        TableName: myTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: _id
            AttributeType: S
        KeySchema:
          - AttributeName: _id 
            KeyType: HASH